#pragma once

#include "ast/Node.h"
#include "ast/ControlStructure.h"
#include "ast/expression/Affectation.h"
#include "ast/expression/Array.h"
#include "ast/expression/Binary.h"
#include "ast/expression/Const.h"
#include "ast/expression/Expression.h"
#include "ast/expression/FunctionCall.h"
#include "ast/expression/Ternary.h"
#include "ast/expression/Unary.h"
#include "ast/expression/Variable.h"
#include "ast/DoWhileInstr.h"
#include "ast/ForInstr.h"
#include "ast/Function.h"
#include "ast/IfInstr.h"
#include "ast/Instruction.h"
#include "ast/NullInstr.h"
#include "ast/Return.h"
#include "ast/Scope.h"
#include "ast/WhileInstr.h"
#include "ast/Block.h"
#include "ast/Break.h"
#include "SymbolTable.h"


